### ISSUE TITLE
Invalid sequence token

### ISSUE THREAD

**Issue by shawnhind** [maxbanton/cwh#58] opened 2019-01-02 18:22 UTC
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
I think that it's a bug.  I see that this issue was also reported in #55 and the person there says it was fixed but I'm still getting this issue.

* **What is the current behavior?**
When using this has the handler for my monolog instance I intermittently get "invalid sequence token" errors returned from AWS.  It seems like this happens when there are connections open and writing to the stream at the same time.

* **What is the expected behavior?**
Should successfully write to the log.

* **Please tell about your environment:**
  
  - PHP Version: 7.2 with cwh version 1.1.10
  - Operating system (distro): Amazon Linux
  - Application mode (web app / cli app / daemon cli app): job running daemon in laravel.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links to have context, eg. stackoverflow, etc)

`exception 'Aws\CloudWatchLogs\Exception\CloudWatchLogsException' with message 'Error executing "PutLogEvents" on "https://logs.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://logs.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"InvalidSequenceTokenException","expectedSequenceToken":"4959143730787630021320614391808164829339315... (truncated...)
 InvalidSequenceTokenException (client): The given sequenceToken is invalid. The next expected sequenceToken is: 49591437307876300213206143918081648293393151102... - {"__type":"InvalidSequenceTokenException","expectedSequenceToken":"49591437307876300213206143918081648293393151...","message":"The given sequenceToken is invalid. The next expected sequenceToken is: 4959143730787630021320614391808..."}'`

**Comment by avramovic** [comment] 2019-02-21 23:02
Duplicate of https://github.com/maxbanton/cwh/issues/55 ?

**Comment by shawnhind** [comment] 2019-02-22 14:28
I sold this issue on our side by having each daemon, web application instance, etc open up their own stream in the log group and then just making each log group correspond to the application and searching across log groups instead of the log stream files.

**Closed** 2019-03-20 18:58 UTC

**Comment by joshbrw** [comment] 2020-04-17 09:29
I'm also having this issue but unsure how to solve it.
